### ISSUE TITLE
Truncate long quotes in side menu

### ISSUE THREAD

**Issue by benjore** [unfoldingWord/translationCore#5097]
### User Story

As a user, I want the text of my selection truncated in the side menu so that it doesn't appear to run off the side of the menu.

### Features / Specifications

- [x] Whenever there is a selection, Change from using the book name (e.g. `Ephesians 1:1`) to the book abbreviation (e.g. `eph 1:1`)
- [x] Truncate the selection in the side menu if it runs off the side of the menu (it should only take one line)
- [x] Add a pop-over to show the complete quote
- [x] Do not have the side menu scroll left/right
- [x] Change the color of the pop-over to gray with black text (match Lexicon pop-up colors)

### Definition of Done

- [ ]
- [ ]
- [ ]

### Mockups

Bad:
![Screen Shot 2018-09-21 at 10.03.22 AM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/2e325dd2-92b8-4e70-ba8b-3cdf793db22f)

Good (from 0.9.1):
![Screen Shot 2018-09-21 at 10.11.42 AM.png](https://images.zenhubusercontent.com/55e5f3984f7a08fbb7f4a658/dcbd50b7-3560-4146-8e30-81c29882a6b1)

**Comment by da1nerd** [comment]
sort of blocked by #5185.
I can work in a branch without those offending bug, but will have to wait until a fix is made before it can be merged in.

**Comment by mannycolon** [comment]
This is how my package.json looks like after I install your branch in release-v1.0.2
```js
{
    ...,
    "tc-ui-toolkit": "github:translationCoreApps/tc-ui-toolkit#bugfix/joel/5097/truncate-quotes",
    ...
}
```

**Comment by mannycolon** [comment]
@neutrinog Friendly reminder that after I merged `translationCoreApps/tc-ui-toolkit#62 ` I guess you will have to publish the new `tc-uitoolkit` version to `npm` and make a PR to add the changes to tC. ()

**Comment by da1nerd** [comment]
@mannycolon thanks for the reminder. Here's a pr https://github.com/unfoldingWord-dev/translationCore/pull/5263

**Comment by da1nerd** [comment]
Oops. I missed a few of the requirements when I first start on this issue. Here's some updates https://github.com/translationCoreApps/tc-ui-toolkit/pull/72

**Comment by cckozie** [comment]
1.0.2 (a5a105b)
You missed the last requirement in the top comment. The popover background is not the same color as that of the Lexicon.
![image](https://user-images.githubusercontent.com/8171759/47379343-42591780-d6c0-11e8-95f2-50e0e2558c40.png)

![image](https://user-images.githubusercontent.com/8171759/47379355-4d13ac80-d6c0-11e8-9941-aa3f918b9f29.png)

**Comment by da1nerd** [comment]
Lines 48 and 52 in `src/GroupMenu/GroupMenu.styles.css` need to be updated to use the correct color.

**Comment by da1nerd** [comment]
Turns out I forgot to mark my styles changes as `!important` so they were not taking effect.

**Comment by PhotoNomad0** [comment]
@neutrinog  - I don't see a PR attached, so moving to in remediation.

**Comment by da1nerd** [comment]
now connected!

**Comment by PhotoNomad0** [comment]
@cckozie - from @neutrinog  in PR

Here are the builds:

https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x32-1.0.2-a18aef8.setup.exe
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-a18aef8.setup.exe
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-macos-x64-1.0.2-a18aef8.dmg
https://tc-builds.door43.org/build/release-v1.0.2/translationCore-linux-x64-1.0.2-a18aef8.deb

**Comment by cckozie** [comment]
In the latest build, 1.0.2 (b84794c), the popovers do not show at all.
Not sure what is happening here. I closed and reopened the project and now I see them. It appears that they do not appear for selections made during the current session of the project in tW.
After more testing I can't really find a pattern for when they show and when they don't.
![image](https://user-images.githubusercontent.com/8171759/47511161-3c3d7500-d83f-11e8-948d-44d5082b15fe.png)

**Comment by da1nerd** [comment]
@cckozie those errors in the screenshot are unrelated to this popup. Also I tested the popup and could not replicate it not displaying. I used the same version of the application as you. 
@neutrinog It may not be related, but every time the popups are not being displayed I see those error in the console.

**Comment by PhotoNomad0** [comment]
@cckozie - Testing on windows, I Opened up the aligned EN ULT of Romans.  I am getting the error of the popup not showing Romans.  Using latest 1.0.2 (3943b93).  @neutrinog

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - testing on mac (same build 1.0.2 (3943b93)), the popups are working!  But not for WIndows.

**Comment by cckozie** [comment]
On Mac
1. Import this project [41-MAT.usfm.zip](https://github.com/unfoldingWord-dev/translationCore/files/2516431/41-MAT.usfm.zip)
2. Open in tW
3. Navigate to and open the 'forgive...' group
4. Click on the first instance of 6:14 in the menu (do not select anything)
5. Click on the first instance of 6:15 in the menu
6. Drag to select the words 'not forgive their trespasses' 
7. Click Save
8. Hover over the verse and notice that the popup does not show
If you close and then reopen the project you will see the popovers.

**Comment by PhotoNomad0** [comment]
@cckozie @neutrinog - But even in Titus on Mac, popups work initially and then stop working after moving around to different words.

**Comment by da1nerd** [comment]
ok thanks. I was able to reproduce and fix it.

**Comment by da1nerd** [comment]
Rather than having multiple PRs I have a [single PR](https://github.com/translationCoreApps/tc-ui-toolkit/pull/87) addressing this issue and https://github.com/unfoldingWord-dev/translationCore/issues/5140

**Comment by PhotoNomad0** [comment]
@neutrinog - I think this is in 1.0.2 now - just needs to be verified that it is in the latest build.

**Comment by PhotoNomad0** [comment]
@cckozie - popups and truncation are working for me.  Tested windows build:

https://tc-builds.door43.org/build/release-v1.0.2/translationCore-win-x64-1.0.2-8c6f266.setup.exe

**Comment by cckozie** [comment]
1.0.2 (5ebb84f) 
I'm not sure that the popup should show when the selection has not been truncated, but since that was not clearly defined in the requirements I'm going to pass it anyway.
