### ISSUE TITLE
Allow multiple tN's for the same verse with the same original language text

### ISSUE THREAD

**Issue by cckozie** [unfoldingWord/translationCore#7096]
[en_tn_50-EPH.tsv.zip](https://github.com/unfoldingWord/translationCore/files/5029827/en_tn_50-EPH.tsv.zip)
Not sue if this is a bug or feature request.
I ran across this "duplicate" check in tN's for Ephesians. When I pinged the content team, they (Larry) indicated that this is a desired use case, and he thought it would work since both notes had a unique ID. As a workaround he will slightly modify one of the notes, but would like this to be supported.
In 3.0, tC highlights both checks at the same time, and selections made on either of the highlighted checks always are displayed on the first of the two checks.
![image.png](https://images.zenhubusercontent.com/56e1a9316caf56c9d38d8df5/e92ac97d-125d-44e5-97d0-079bdb1f594a)

**Comment by PhotoNomad0** [comment]
Developer Notes:
- in checking-tool-wrapper will have to update methods doing matching to also use check's ID:
  - see Api._loadCheckData()
  - checkDataHelpers.loadCheckData()
  - contextIdHelpers.sameContext()
  - groupsDataActions.isCheckUnique()
  - groupDataHelpers.findGroupDataItem()
- Looks like import from catalog will have to be updated to parse the check's ID:
  - update tsv-groupdata-parser to pull in ID
  - update tc-source-content-validator with latest tsv-groupdata-parser
- will have migration of checks for tN that were saved without ID
- will have to update bundled resources.  THis will re-process tN selections and records to add ID field from the tsv.

**Comment by PhotoNomad0** [comment]
Question: do we want to add the ID field to CSV export?

**Comment by birchamp** [comment]
@da1nerd @PhotoNomad0 Yes, I'd say if someone wants a CSV then they could have a reason for the ID field.

**Comment by da1nerd** [comment]
@PhotoNomad0 it looks like I can add the missing note id somewhere in here https://github.com/unfoldingWord/tsv-groupdata-parser/blob/master/src/tsvToGroupData.js#L273-L286. That should propagate to all the different update methods, including the bundled resources (because github actions updates this automatically).

Could you double check that you've identified all of the locations where we'll need to update the note matching in [your comment above](https://github.com/unfoldingWord/translationCore/issues/7096#issuecomment-692798204)? I barely worked on this area and don't really know where to look.

**Comment by da1nerd** [comment]
Ok, I have a PR ready for review that should solve this problem. It took some exploring, but in the end there was no need to add any data migrations or many large changes. All of the changes to related projects are published under `alpha` tags and we'll need to make sure to get those changes into master/develop branches after this is approved.
https://github.com/unfoldingWord/translationCore/pull/7128

This does not include anything in the CSV output. @PhotoNomad0 do you where to add that?

**Comment by PhotoNomad0** [comment]
@da1nerd 
It looks like you will just need to add an entry for checkID here: https://github.com/unfoldingWord/translationCore/blob/develop/src/js/helpers/csvHelpers.js#L114

But you should put an empty string there if checkID is undefined, since tWords does not have that field.

https://github.com/unfoldingWord/translationCore/pull/7128 At first glance it works well.  Windows build is still failing

**Comment by PhotoNomad0** [comment]
@da1nerd 
- It looks like en_tn got updated so it does not use the exact same original language quote, so it "fixes" the above example. 
- Larry mentioned another 1T1 6:19 - Metaphors (figs-metaphor) that is still failing.  So your fixes do not yet fix the underlying problem.

**Comment by PhotoNomad0** [comment]
@da1nerd - I am pushing back on content team for 1T1 6:19 - Metaphors example since that looks like a duplicated check.

**Comment by da1nerd** [comment]
ok, it would really help if we had an example that wasn't fixed.

**Comment by PhotoNomad0** [comment]
You can use  1T1 6:19 referenced above.  I got word back that it is remaining.

**Comment by PhotoNomad0** [comment]
Note: 
- testing https://git.door43.org/lrsallee/en_ult_1ti_book
- interesting that duplicate entries are showing the same checkID in the groupedMenu.
- backing up to GroupMenuComponent, the duplicate entries are showing the same checkID
- looking in the index entry for metaphors there are two entries with same checkID, so suspect problem with how checkID entries were added to index:
```
      "reference": {
        "bookId": "1ti",
        "chapter": 6,
        "verse": 19
      },
      "tool": "translationNotes",
      "groupId": "figs-metaphor",
      "checkId": "t493",
```
- looking in ~/translationCore/resources/en/translationHelps/translationNotes/v34/figures/groups/1ti/figs-metaphor.json I see that the first entry should be `"checkId": "zc9d"`, so it looks like the checkID of first entry is being clobbered on download of project.
- checkID is being added in openProject(), looks like copyGroupDataToProject() is doing it. Looks like it is happening in project.importCategoryGroupData().  Looks like the culprit is ProjectAPI.isMatchingCheckInstance() which is ignoring checkId.

**Comment by PhotoNomad0** [comment]
@da1nerd Here is a fix to tCore ProjectAPI.isMatchingCheckInstance() that does a better job updating existing project data and at the same time recognizing checkId for checks that use them:
```
  /**
   * returns true if the contextId's are for the same check instance
   * @param {Object} existingContextId
   * @param {Object} newContextId
   * @return {boolean}
   */
  isMatchingCheckInstance(existingContextId, newContextId) {
    if (!existingContextId.checkId) { // tricky: doing tWords check or project migration case where old project that did not have checkId.  In the migration case we will match first entry that is same except for checkId.
      return (isEqual(existingContextId.reference, newContextId.reference) &&
        (existingContextId.occurrence === newContextId.occurrence) &&
        (
          (existingContextId.quoteString && newContextId.quoteString ? (existingContextId.quoteString === newContextId.quoteString) : // compare quoteString if present
            isEqual(existingContextId.quote, newContextId.quote)) // else compare quote array
        )
      );
    }
    return (isEqual(existingContextId.reference, newContextId.reference) &&
      (existingContextId.occurrence === newContextId.occurrence) &&
      (existingContextId.checkId === newContextId.checkId) &&
      (
        (existingContextId.quoteString && newContextId.quoteString ? (existingContextId.quoteString === newContextId.quoteString) : // compare quoteString if present
          isEqual(existingContextId.quote, newContextId.quote)) // else compare quote array
      )
    );
  }
```

would be good to add a unit test for migration case.

will also need to fix in checking-tool-wrapper/lib/helpers/ProjectAPI.js

**Comment by da1nerd** [comment]
@PhotoNomad0 I've made some changes and think everything is working now. Please review https://github.com/unfoldingWord/translationCore/pull/7128 again

**Comment by PhotoNomad0** [comment]
Testing: translationCore 3.0.2 (7a830de)

**Comment by PhotoNomad0** [comment]
@cckozie @elsylambert 
Fixes are in translationCore 3.0.2 (7a830de) (download from Zulip github screen). See test instructions in  https://github.com/unfoldingWord/translationCore/pull/7158 for project I used for testing duplicate.  When you open a project in 3.0.2 the project data will be migrated so you can no longer open in older tCore versions.

**Comment by elsylambert** [comment]
Looks good in translationCore 3.0.2 (f02bb0). Multiple tNs works fine for the same verse.

**Comment by gayathrihayden** [comment]
Fix tested in tC 3.0.2 build 18ad847 and works fine. 

Checked https://github.com/unfoldingWord/translationCore/pull/7158 and the link to https://git.door43.org/lrsallee/en_ult_1ti_book did not work 

Manually imported 1 Timothy as a local project and observed that 1 Tim 6:19 (category "Metaphor ") can be selected individually

This fix also seems to resolve https://git.door43.org/unfoldingWord/en_tn/issues/2125. The verses that appears multiple times can now be selected individually
